<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Predicting heart disease</title>

<script src="site_libs/header-attrs-2.13/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">REINPETER MOMANYI</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-cogs"></span>
     
    Machine Learning
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Predicting-heart-disease.html">Logistic Regression: Predicting heart disease</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="fa fa-chalkboard-teacher"></span>
     
    Dashboards
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="https://reinp-momz.shinyapps.io/2019CENSUS_KEN_Shinydashboard/">2019 Kenya Census - Shinydashboard</a>
    </li>
    <li>
      <a href="https://reinp-momz.shinyapps.io/NSE_Trading_Flexdashboard_Shiny/">Nairobi Securities Exchange - Flexdashboard</a>
    </li>
    <li>
      <a href="https://reinp-momz.shinyapps.io/COVID-19_Flexdashboard_Shiny/">COVID-19 - Flexdashboard</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="cv.html">
    <span class="fa fa-file-pdf"></span>
     
    CV
  </a>
</li>
<li>
  <a href="https://github.com/reinpmomz">
    <span class="fab fa-github"></span>
     
    GitHub
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/reinpeter-ondeyo-19b50b1a/">
    <span class="fab fa-linkedin"></span>
     
    LinkedIn
  </a>
</li>
<li>
  <a href="mailto:reinp.mom@gmail.com">
    <span class="fa fa-envelope"></span>
     
    Contact me
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Predicting heart disease</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#introduction"><span class="toc-section-number">1</span> Introduction</a>
<ul>
<li><a href="#overview"><span class="toc-section-number">1.1</span> Overview</a></li>
<li><a href="#about-the-data"><span class="toc-section-number">1.2</span> About the Data</a></li>
</ul></li>
<li><a href="#data-exploration"><span class="toc-section-number">2</span> Data Exploration</a>
<ul>
<li><a href="#loading-relevant-packages"><span class="toc-section-number">2.1</span> loading Relevant packages</a></li>
<li><a href="#loading-data-set"><span class="toc-section-number">2.2</span> loading Data Set</a></li>
<li><a href="#converting-into-factors"><span class="toc-section-number">2.3</span> Converting into factors</a></li>
<li><a href="#checking-missing-values"><span class="toc-section-number">2.4</span> checking missing values</a></li>
</ul></li>
<li><a href="#exploratory-data-analysis"><span class="toc-section-number">3</span> Exploratory data analysis</a>
<ul>
<li><a href="#univariate-analysis"><span class="toc-section-number">3.1</span> Univariate analysis</a>
<ul>
<li><a href="#descriptives-frequency-table"><span class="toc-section-number">3.1.1</span> Descriptives Frequency table</a></li>
<li><a href="#visualization"><span class="toc-section-number">3.1.2</span> Visualization</a></li>
</ul></li>
<li><a href="#bivariate-analysis"><span class="toc-section-number">3.2</span> Bivariate analysis</a>
<ul>
<li><a href="#difference-frequency-table"><span class="toc-section-number">3.2.1</span> Difference Frequency table</a></li>
<li><a href="#visualization-1"><span class="toc-section-number">3.2.2</span> Visualization</a></li>
<li><a href="#correlation"><span class="toc-section-number">3.2.3</span> Correlation</a></li>
</ul></li>
</ul></li>
<li><a href="#logistic-regression"><span class="toc-section-number">4</span> Logistic Regression</a>
<ul>
<li><a href="#splitting-the-data-for-training-and-testing"><span class="toc-section-number">4.1</span> Splitting the data for training and testing</a></li>
<li><a href="#model"><span class="toc-section-number">4.2</span> model</a></li>
<li><a href="#model-statistics"><span class="toc-section-number">4.3</span> model statistics</a></li>
<li><a href="#model-results"><span class="toc-section-number">4.4</span> model results</a></li>
</ul></li>
<li><a href="#evaluating-our-model"><span class="toc-section-number">5</span> Evaluating our Model</a>
<ul>
<li><a href="#fitting-with-testing-data"><span class="toc-section-number">5.1</span> Fitting with testing data</a></li>
<li><a href="#confussion-matrix"><span class="toc-section-number">5.2</span> Confussion matrix</a></li>
<li><a href="#roc-curve"><span class="toc-section-number">5.3</span> ROC curve</a></li>
</ul></li>
</ul>
</div>

<div id="introduction" class="section level1" number="1">
<h1 number="1"><span class="header-section-number">1</span> Introduction</h1>
<div id="overview" class="section level2" number="1.1">
<h2 number="1.1"><span class="header-section-number">1.1</span> Overview</h2>
<p>Cardiovascular diseases (CVDs) are the number 1 cause of death globally, taking an estimated 17.9 million lives each year, which accounts for 31% of all deaths worldwide. Four out of 5CVD deaths are due to heart attacks and strokes, and one-third of these deaths occur prematurely in people under 70 years of age. This makes it important for health facilities to be able to predict occurrences of heart diseases in order to make plans for early treatment (Assmann et al. 2005). Heart failure is a common event caused by CVDs and this dataset contains 11 features that can be used to predict a possible heart disease.</p>
<p>People with cardiovascular disease or who are at high cardiovascular risk (due to the presence of one or more risk factors such as hypertension, diabetes, hyperlipidaemia or already established disease) need early detection and management wherein a machine learning model can be of great help.</p>
</div>
<div id="about-the-data" class="section level2" number="1.2">
<h2 number="1.2"><span class="header-section-number">1.2</span> About the Data</h2>
<p>This dataset contains 918 observations with 12 features. The data dictionary is as follows:</p>
<ul>
<li>output: target variable (1=has heart attack, 0= has no heart attack)</li>
<li>age: Age of the patient</li>
<li>sex: Sex of the patient (1= male, 0= female).</li>
<li>cp: chest pain type (0=typical angina, 1=atypical angina, 2=non-anginal and 3=asymptomatic)</li>
<li>trtbps: resting blood pressure (in mm Hg)</li>
<li>chol: cholestoral in mg/dl fetched via BMI sensor</li>
<li>fbs: fasting blood sugar (&gt;120mg/dl=1, &lt;= 120mg/dl=0).</li>
<li>restecg: resting electrocardiographic results( 0=normal, 1=having ST-T wave abnormality, 2=showing probable or definate left ventricular hypertrophy by Este’s criteria.)</li>
<li>thalach: Maximum heart rate achieved.</li>
<li>exng: exercise induced angina; 1=yes, 0=no.</li>
<li>oldpeak: ST depression.</li>
<li>slp = slope of peak exercise; 0=upsloping, 1=flat, 2=downsloping.</li>
</ul>
</div>
</div>
<div id="data-exploration" class="section level1" number="2">
<h1 number="2"><span class="header-section-number">2</span> Data Exploration</h1>
<div id="loading-relevant-packages" class="section level2" number="2.1">
<h2 number="2.1"><span class="header-section-number">2.1</span> loading Relevant packages</h2>
<pre class="r"><code>#Import relevant packages

library(tidyverse)
library(janitor)
library(readr)
library(plotly)
library(knitr)</code></pre>
</div>
<div id="loading-data-set" class="section level2" number="2.2">
<h2 number="2.2"><span class="header-section-number">2.2</span> loading Data Set</h2>
<pre class="r"><code>heart_disease &lt;- read_csv(&#39;https://raw.githubusercontent.com/reinpmomz/Predicting-heart-disease/main/data/heart.csv&#39;)%&gt;%
  clean_names()


#View(heart_disease)
head(heart_disease)</code></pre>
<pre><code>## # A tibble: 6 x 12
##     age   sex    cp trtbps  chol   fbs restecg thalach  exng oldpeak   slp
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1    40     1     1    140   289     0       0     172     0     0       0
## 2    49     0     2    160   180     0       0     156     0     1       1
## 3    37     1     1    130   283     0       1      98     0     0       0
## 4    48     0     3    138   214     0       0     108     1     1.5     1
## 5    54     1     2    150   195     0       0     122     0     0       0
## 6    39     1     2    120   339     0       0     170     0     0       0
## # ... with 1 more variable: output &lt;dbl&gt;</code></pre>
<pre class="r"><code>##checking the data structure

str(heart_disease)</code></pre>
<pre><code>## spec_tbl_df [918 x 12] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ age    : num [1:918] 40 49 37 48 54 39 45 54 37 48 ...
##  $ sex    : num [1:918] 1 0 1 0 1 1 0 1 1 0 ...
##  $ cp     : num [1:918] 1 2 1 3 2 2 1 1 3 1 ...
##  $ trtbps : num [1:918] 140 160 130 138 150 120 130 110 140 120 ...
##  $ chol   : num [1:918] 289 180 283 214 195 339 237 208 207 284 ...
##  $ fbs    : num [1:918] 0 0 0 0 0 0 0 0 0 0 ...
##  $ restecg: num [1:918] 0 0 1 0 0 0 0 0 0 0 ...
##  $ thalach: num [1:918] 172 156 98 108 122 170 170 142 130 120 ...
##  $ exng   : num [1:918] 0 0 0 1 0 0 0 0 1 0 ...
##  $ oldpeak: num [1:918] 0 1 0 1.5 0 0 0 0 1.5 0 ...
##  $ slp    : num [1:918] 0 1 0 1 0 0 0 0 1 0 ...
##  $ output : num [1:918] 0 1 0 1 0 0 0 0 1 0 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   age = col_double(),
##   ..   sex = col_double(),
##   ..   cp = col_double(),
##   ..   trtbps = col_double(),
##   ..   chol = col_double(),
##   ..   fbs = col_double(),
##   ..   restecg = col_double(),
##   ..   thalach = col_double(),
##   ..   exng = col_double(),
##   ..   oldpeak = col_double(),
##   ..   slp = col_double(),
##   ..   output = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<p>From the output on the data structure, all of the data has been read as numeric values(‘double’ value or a decimal type with at least two decimal places) but some should be converted to factors since they are categorical.</p>
</div>
<div id="converting-into-factors" class="section level2" number="2.3">
<h2 number="2.3"><span class="header-section-number">2.3</span> Converting into factors</h2>
<pre class="r"><code>heart_disease_final &lt;- heart_disease%&gt;%
  mutate(output= factor(output, levels = c(0,1), 
                                      labels = c(&quot;No heart attack&quot;, &quot;Has Heart attack&quot;)))%&gt;%
  mutate(sex= factor(sex, levels = c(0,1), 
                                      labels = c(&quot;Female&quot;, &quot;Male&quot;)))%&gt;%
  mutate(cp= factor(cp, levels = c(0,1,2,3), 
          labels = c(&quot;typical angina&quot;, &quot;atypical angina&quot;, &quot;non-anginal&quot;, &quot;asymptomatic&quot;)))%&gt;%
  mutate(fbs= factor(fbs, levels = c(0,1), 
                                      labels = c(&quot;&lt;= 120mg/dl&quot;, &quot;&gt;120mg/dl&quot;)))%&gt;%
  mutate(restecg= factor(restecg, levels = c(0,1,2), 
          labels = c(&quot;normal&quot;, &quot;having ST_T \n abnormality&quot;, &quot;showing probable or \n definate left\n ventricular hypertrophy&quot;)))%&gt;%
  mutate(exng= factor(exng, levels = c(0,1), 
                                      labels = c(&quot;No&quot;, &quot;Yes&quot;)))%&gt;%
  mutate(slp= factor(slp, levels = c(0,1,2), 
          labels = c(&quot;upsloping&quot;, &quot;flat&quot;, &quot;downsloping&quot;)))%&gt;%
  filter(trtbps&gt;0)%&gt;%
  filter(chol&gt;0)</code></pre>
<pre class="r"><code>var.labels = c(
  age = &quot;Age of the patient&quot;,
  sex = &quot;Sex of the patient&quot;,
  cp = &quot;Chest pain type&quot;,
  trtbps = &quot;Resting blood pressure (in mm Hg)&quot;,
  chol = &quot;Cholestoral in mg/dl&quot;,
  fbs = &quot;Fasting blood sugar&quot;,
  restecg = &quot;Resting electrocardiographic results&quot;,
  thalach = &quot;Maximum heart rate achieved&quot;,
  exng = &quot;Exercise induced angina&quot;,
  oldpeak = &quot;ST depression&quot;,
  slp = &quot;Slope of peak exercise&quot;,
  output = &quot;Heart disease&quot;)

heart_disease_final &lt;- labelled::set_variable_labels(heart_disease_final, .labels = var.labels)

str(heart_disease_final)</code></pre>
<pre><code>## tibble [746 x 12] (S3: tbl_df/tbl/data.frame)
##  $ age    : num [1:746] 40 49 37 48 54 39 45 54 37 48 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Age of the patient&quot;
##  $ sex    : Factor w/ 2 levels &quot;Female&quot;,&quot;Male&quot;: 2 1 2 1 2 2 1 2 2 1 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Sex of the patient&quot;
##  $ cp     : Factor w/ 4 levels &quot;typical angina&quot;,..: 2 3 2 4 3 3 2 2 4 2 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Chest pain type&quot;
##  $ trtbps : num [1:746] 140 160 130 138 150 120 130 110 140 120 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Resting blood pressure (in mm Hg)&quot;
##  $ chol   : num [1:746] 289 180 283 214 195 339 237 208 207 284 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Cholestoral in mg/dl&quot;
##  $ fbs    : Factor w/ 2 levels &quot;&lt;= 120mg/dl&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Fasting blood sugar&quot;
##  $ restecg: Factor w/ 3 levels &quot;normal&quot;,&quot;having ST_T \n abnormality&quot;,..: 1 1 2 1 1 1 1 1 1 1 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Resting electrocardiographic results&quot;
##  $ thalach: num [1:746] 172 156 98 108 122 170 170 142 130 120 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Maximum heart rate achieved&quot;
##  $ exng   : Factor w/ 2 levels &quot;No&quot;,&quot;Yes&quot;: 1 1 1 2 1 1 1 1 2 1 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Exercise induced angina&quot;
##  $ oldpeak: num [1:746] 0 1 0 1.5 0 0 0 0 1.5 0 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;ST depression&quot;
##  $ slp    : Factor w/ 3 levels &quot;upsloping&quot;,&quot;flat&quot;,..: 1 2 1 2 1 1 1 1 2 1 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Slope of peak exercise&quot;
##  $ output : Factor w/ 2 levels &quot;No heart attack&quot;,..: 1 2 1 2 1 1 1 1 2 1 ...
##   ..- attr(*, &quot;label&quot;)= chr &quot;Heart disease&quot;</code></pre>
<p>The categorial columns are sex, cp, fbs, restecg, exng, slp while continuous columns are age, trtbps, chol, thalach, oldpeak and target variable is output</p>
</div>
<div id="checking-missing-values" class="section level2" number="2.4">
<h2 number="2.4"><span class="header-section-number">2.4</span> checking missing values</h2>
<pre class="r"><code>mean(is.na(heart_disease_final))</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>#which(is.na(heart_disease_final))

#which(!complete.cases(heart_disease_final))</code></pre>
<p>There were no missing values in our data set.</p>
</div>
</div>
<div id="exploratory-data-analysis" class="section level1" number="3">
<h1 number="3"><span class="header-section-number">3</span> Exploratory data analysis</h1>
<p>Exploring data is vital in giving a clue of the expected relationship between the dependent variable and the exploratory variables (Zuur et al. 2010).</p>
<div id="univariate-analysis" class="section level2" number="3.1">
<h2 number="3.1"><span class="header-section-number">3.1</span> Univariate analysis</h2>
<p>This is analysis of one variable to enable us understand the distribution of values for a single variable.</p>
<div id="descriptives-frequency-table" class="section level3" number="3.1.1">
<h3 number="3.1.1"><span class="header-section-number">3.1.1</span> Descriptives Frequency table</h3>
<pre class="r"><code>library(gtsummary)
library(flextable)

set_gtsummary_theme(list(
  &quot;tbl_summary-fn:percent_fun&quot; = function(x) style_percent(x, digits = 1),
  &quot;tbl_summary-str:categorical_stat&quot; = &quot;{n} ({p}%)&quot;
))
# Setting `Compact` theme
theme_gtsummary_compact()</code></pre>
<pre class="r"><code># make dataset with variables to summarize

      
tbl_summary(heart_disease_final,
                      type = list(
                        all_dichotomous() ~ &quot;categorical&quot;,
                         all_continuous() ~ &quot;continuous2&quot;)
                      , statistic = all_continuous() ~ c(
                                     &quot;{mean} ({sd})&quot;, 
                                     &quot;{median} ({p25}, {p75})&quot;, 
                                     &quot;{min}, {max}&quot;)
                      , digits = all_continuous() ~ 2
                      , missing = &quot;always&quot; # don&#39;t list missing data separately
                      ,missing_text = &quot;Missing&quot;
                      ) %&gt;% 
  modify_header(label = &quot;**Descriptives**&quot;) %&gt;% # update the column header
  bold_labels() %&gt;%
  italicize_levels()%&gt;%
  add_n() # add column with total number of non-missing observations</code></pre>
<div id="lbktiforhv" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#lbktiforhv .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 13px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#lbktiforhv .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lbktiforhv .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#lbktiforhv .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#lbktiforhv .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lbktiforhv .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lbktiforhv .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#lbktiforhv .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#lbktiforhv .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#lbktiforhv .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#lbktiforhv .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#lbktiforhv .gt_group_heading {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#lbktiforhv .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#lbktiforhv .gt_from_md > :first-child {
  margin-top: 0;
}

#lbktiforhv .gt_from_md > :last-child {
  margin-bottom: 0;
}

#lbktiforhv .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#lbktiforhv .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#lbktiforhv .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#lbktiforhv .gt_row_group_first td {
  border-top-width: 2px;
}

#lbktiforhv .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#lbktiforhv .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#lbktiforhv .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#lbktiforhv .gt_last_summary_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lbktiforhv .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#lbktiforhv .gt_first_grand_summary_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#lbktiforhv .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#lbktiforhv .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lbktiforhv .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lbktiforhv .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 1px;
  padding-right: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#lbktiforhv .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lbktiforhv .gt_sourcenote {
  font-size: 90%;
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#lbktiforhv .gt_left {
  text-align: left;
}

#lbktiforhv .gt_center {
  text-align: center;
}

#lbktiforhv .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#lbktiforhv .gt_font_normal {
  font-weight: normal;
}

#lbktiforhv .gt_font_bold {
  font-weight: bold;
}

#lbktiforhv .gt_font_italic {
  font-style: italic;
}

#lbktiforhv .gt_super {
  font-size: 65%;
}

#lbktiforhv .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#lbktiforhv .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#lbktiforhv .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#lbktiforhv .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#lbktiforhv .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Descriptives</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>N = 746</strong><sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Age of the patient</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Mean (SD)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">52.88 (9.51)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Median (IQR)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">54.00 (46.00, 59.00)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Range</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">28.00, 77.00</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Sex of the patient</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Female</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">182 (24.4%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Male</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">564 (75.6%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Chest pain type</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">typical angina</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">41 (5.50%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">atypical angina</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">166 (22.3%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">non-anginal</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">169 (22.7%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">asymptomatic</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">370 (49.6%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Resting blood pressure (in mm Hg)</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Mean (SD)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">133.02 (17.28)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Median (IQR)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">130.00 (120.00, 140.00)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Range</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">92.00, 200.00</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Cholestoral in mg/dl</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Mean (SD)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">244.64 (59.15)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Median (IQR)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">237.00 (207.25, 275.00)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Range</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">85.00, 603.00</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Fasting blood sugar</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">&lt;= 120mg/dl</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">621 (83.2%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">&gt;120mg/dl</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">125 (16.8%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Resting electrocardiographic results</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">normal</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">445 (59.7%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">having ST_T 
 abnormality</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">125 (16.8%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">showing probable or 
 definate left
 ventricular hypertrophy</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">176 (23.6%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Maximum heart rate achieved</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Mean (SD)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">140.23 (24.52)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Median (IQR)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">140.00 (122.00, 160.00)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Range</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">69.00, 202.00</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Exercise induced angina</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">No</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">459 (61.5%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Yes</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">287 (38.5%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">ST depression</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Mean (SD)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.90 (1.07)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Median (IQR)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.50 (0.00, 1.50)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Range</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">-0.10, 6.20</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Slope of peak exercise</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">upsloping</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">349 (46.8%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">flat</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">354 (47.5%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">downsloping</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">43 (5.76%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Heart disease</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">No heart attack</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">390 (52.3%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Has Heart attack</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">356 (47.7%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="3"><sup class="gt_footnote_marks">1</sup> n (%)</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
<div id="visualization" class="section level3" number="3.1.2">
<h3 number="3.1.2"><span class="header-section-number">3.1.2</span> Visualization</h3>
<pre class="r"><code>library(ggpubr)

p1 &lt;- ggplot(heart_disease_final, aes(x=output))+
  geom_bar(aes(fill = output), show.legend = FALSE)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Heart disease&quot;)+
  geom_text(aes(label = ..count..), stat = &quot;count&quot;, vjust = 1.5, colour = &quot;black&quot;)+
  #guides(fill = FALSE)+
  theme_pubclean()+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        #legend.position = &quot;none&quot;,
        axis.text.y = element_text(color=&quot;black&quot;,size=12),
        axis.text.x = element_text(color=&quot;black&quot;,size=11),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())

p2 &lt;- ggplot(heart_disease_final, aes(x=sex))+
  geom_bar(aes(fill = sex), show.legend = FALSE)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Sex of the patient&quot;)+
  scale_y_continuous(breaks = seq(0, 600, by = 100), limits = c(0, 600))+
  theme_pubclean()+
  geom_text(aes(label = ..count..), stat = &quot;count&quot;, vjust = 1.5, colour = &quot;black&quot;)+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())

p3 &lt;- ggplot(heart_disease_final, aes(x=cp))+
  geom_bar(aes(fill = cp), show.legend = FALSE)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Chest pain Type&quot;)+
  scale_y_continuous(breaks = seq(0, 400, by = 50), limits = c(0, 400))+
  theme_pubclean()+
  geom_text(aes(label = ..count..), stat = &quot;count&quot;, vjust = 1.5, colour = &quot;black&quot;)+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        axis.text.y = element_text(color=&quot;black&quot;,size=12),
        axis.text.x = element_text(color=&quot;black&quot;,size=12, angle = 90),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())


p4 &lt;- ggplot(heart_disease_final, aes(x=fbs))+
  geom_bar(aes(fill = fbs), show.legend = FALSE)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Fasting blood sugar&quot;)+
  scale_y_continuous(breaks = seq(0, 750, by = 100), limits = c(0, 750))+
 theme_pubclean()+
  geom_text(aes(label = ..count..), stat = &quot;count&quot;, vjust = 1.5, colour = &quot;black&quot;)+
  theme(axis.title= element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())

p5 &lt;- ggplot(heart_disease_final, aes(x=restecg))+
  geom_bar(aes(fill = restecg), show.legend = FALSE)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Resting electrocardiographic results&quot;)+
  scale_y_continuous(breaks = seq(0, 500, by = 100), limits = c(0, 500))+
  theme_pubclean()+
  geom_text(aes(label = ..count..), stat = &quot;count&quot;, vjust = 1.5, colour = &quot;black&quot;)+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        axis.text.y = element_text(color=&quot;black&quot;,size=12),
        axis.text.x = element_text(color=&quot;black&quot;,size=11, angle = 90),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())

p6 &lt;- ggplot(heart_disease_final, aes(x=exng))+
  geom_bar(aes(fill = exng), show.legend = FALSE)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Exercise induced angina&quot;)+
  scale_y_continuous(breaks = seq(0, 500, by = 100), limits = c(0, 500))+
  theme_pubclean()+
  geom_text(aes(label = ..count..), stat = &quot;count&quot;, vjust = 1.5, colour = &quot;black&quot;)+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())


p7 &lt;- ggplot(heart_disease_final, aes(x=slp))+
  geom_bar(aes(fill = slp), show.legend = FALSE)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Slope of peak exercise&quot;)+
  scale_y_continuous(breaks = seq(0, 400, by = 50), limits = c(0, 400))+
  theme_pubclean()+
  geom_text(aes(label = ..count..), stat = &quot;count&quot;, vjust = 1.5, colour = &quot;black&quot;)+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())


figure1 &lt;- ggarrange(p1, p2, p3, p4, p5, p6, p7, 
          #labels = c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;,&quot;D&quot;, &quot;E&quot;, &quot;F&quot;, &quot;G&quot;),
          ncol = 4, nrow = 2)

annotate_figure(figure1,
                top = text_grob(&quot;Count plots for various categorical features&quot;,
                                color = &quot;red&quot;, face = &quot;bold&quot;, size = 15),
                bottom = text_grob(&quot;Data source: \n heart disease data set&quot;, color = &quot;blue&quot;,
                                   hjust = 1, x = 0.98, face = &quot;italic&quot;, size = 10),
                #left = text_grob(&quot;Figure arranged using ggpubr&quot;, color = &quot;green&quot;, rot = 90),
                #right = &quot;&quot;,
                fig.lab = &quot;Figure 1&quot;, fig.lab.face = &quot;bold&quot;
                )</code></pre>
<p><img src="Predicting-heart-disease_files/figure-html/bar%20graphs-1.png" width="1344" /></p>
<pre class="r"><code>p8 &lt;- ggplot(heart_disease_final, aes(x=age)) + 
  geom_histogram(color=&quot;black&quot;, fill=&quot;white&quot;)+
  geom_vline(aes(xintercept=mean(age)),
            color=&quot;blue&quot;, linetype=&quot;dashed&quot;, size=1)+
  scale_y_continuous(breaks = seq(0, 85, by = 10), limits = c(0, 80))+
  scale_x_continuous(n.breaks = 10)+
  labs(x=&quot;age&quot;,y=&quot;count&quot;, title = &quot;Age of the patient&quot;)+
  theme(axis.title = element_text(color=&quot;black&quot;,size=12),
        axis.text = element_text(color=&quot;black&quot;,size=11),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())

p9 &lt;-ggplot(heart_disease_final, aes(x=trtbps)) + 
  geom_histogram(color=&quot;black&quot;, fill=&quot;lightblue&quot;)+
  geom_vline(aes(xintercept=mean(trtbps)),
            color=&quot;blue&quot;, linetype=&quot;dashed&quot;, size=1)+
   scale_y_continuous(breaks = seq(0, 130, by = 10), limits = c(0, 130))+
  scale_x_continuous(n.breaks = 10)+
  labs(x=&quot;Resting blood pressure (in mm Hg)&quot;,y=&quot;count&quot;, title = &quot;Resting blood pressure&quot;)+
  theme(axis.title = element_text(color=&quot;black&quot;,size=12),
        axis.text = element_text(color=&quot;black&quot;,size=11),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())

p10 &lt;-ggplot(heart_disease_final, aes(x=chol)) + 
  geom_histogram(color=&quot;black&quot;, fill=&quot;pink&quot;)+
  geom_vline(aes(xintercept=mean(chol)),
            color=&quot;blue&quot;, linetype=&quot;dashed&quot;, size=1)+
  scale_y_continuous(breaks = seq(0, 120, by = 10), limits = c(0, 120))+
  scale_x_continuous(n.breaks = 12)+
  labs(x=&quot;cholestoral in mg/dl&quot;,y=&quot;count&quot;, title = &quot;cholestoral&quot;)+
  theme(axis.title = element_text(color=&quot;black&quot;,size=12),
        axis.text = element_text(color=&quot;black&quot;,size=11),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())

p11 &lt;-ggplot(heart_disease_final, aes(x=thalach)) + 
  geom_histogram(color=&quot;black&quot;, fill=&quot;lightgreen&quot;)+
  geom_vline(aes(xintercept=mean(thalach)),
            color=&quot;blue&quot;, linetype=&quot;dashed&quot;, size=1)+
  scale_y_continuous(breaks = seq(0, 80, by = 10), limits = c(0, 80))+
  scale_x_continuous(n.breaks = 12)+
  labs(x=&quot;Maximum heart rate achieved&quot;,y=&quot;count&quot;, title = &quot;Maximum heart rate&quot;)+
  theme(axis.title = element_text(color=&quot;black&quot;,size=12),
        axis.text = element_text(color=&quot;black&quot;,size=11),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())


figure2 &lt;- ggarrange(p8, p9, p10, p11,
          ncol = 2, nrow = 2)

annotate_figure(figure2,
                top = text_grob(&quot;Histograms for various continous features&quot;,
                                color = &quot;red&quot;, face = &quot;bold&quot;, size = 15),
                bottom = text_grob(&quot;Data source: \n heart disease data set&quot;, color = &quot;blue&quot;,
                                   hjust = 1, x = 0.98, face = &quot;italic&quot;, size = 10),
                #left = text_grob(&quot;Figure arranged using ggpubr&quot;, color = &quot;green&quot;, rot = 90),
                #right = &quot;&quot;,
                fig.lab = &quot;Figure 2&quot;, fig.lab.face = &quot;bold&quot;
                )</code></pre>
<p><img src="Predicting-heart-disease_files/figure-html/histograms-1.png" width="1344" /></p>
</div>
</div>
<div id="bivariate-analysis" class="section level2" number="3.2">
<h2 number="3.2"><span class="header-section-number">3.2</span> Bivariate analysis</h2>
<div id="difference-frequency-table" class="section level3" number="3.2.1">
<h3 number="3.2.1"><span class="header-section-number">3.2.1</span> Difference Frequency table</h3>
<pre class="r"><code># make dataset with variables to summarize

      
tbl_summary(heart_disease_final,
             by = output,
                      type = list(
                        all_dichotomous() ~ &quot;categorical&quot;,
                         all_continuous() ~ &quot;continuous2&quot;)
                      , statistic = all_continuous() ~ c(
                                     &quot;{mean} ({sd})&quot;, 
                                     &quot;{median} ({p25}, {p75})&quot;, 
                                     &quot;{min}, {max}&quot;)
                      , digits = all_continuous() ~ 2
                      , missing = &quot;always&quot; # don&#39;t list missing data separately
                      ,missing_text = &quot;Missing&quot;
                      ) %&gt;% 
  modify_header(label = &quot;**Variables**&quot;) %&gt;% # update the column header
  bold_labels() %&gt;%
  italicize_levels()%&gt;%
  add_n()%&gt;% # add column with total number of non-missing observations
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 3),
        c(age, trtbps, chol, thalach, oldpeak) ~ &quot;t.test&quot;,
        test.args = c(age, trtbps, chol, thalach, oldpeak) ~ list(var.equal = TRUE)) %&gt;%
  bold_p(t= 0.05) %&gt;% # bold p-values under a given threshold (default 0.05)
  #add_overall() %&gt;%
  #add_difference() %&gt;% #add column for difference between two group, confidence interval, and p-value
  modify_spanning_header(c(&quot;stat_1&quot;, &quot;stat_2&quot;) ~ &quot;**Heart Disease**&quot;)  %&gt;%
  #modify_caption(&quot;**Table 1. Patient Characteristics**&quot;)%&gt;%
  modify_footnote(
    all_stat_cols() ~ &quot;Mean (SD); Median (IQR); Range; Frequency (%)&quot;
  )</code></pre>
<div id="nodnscgwqe" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#nodnscgwqe .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 13px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#nodnscgwqe .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nodnscgwqe .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#nodnscgwqe .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#nodnscgwqe .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nodnscgwqe .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nodnscgwqe .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#nodnscgwqe .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#nodnscgwqe .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#nodnscgwqe .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#nodnscgwqe .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#nodnscgwqe .gt_group_heading {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#nodnscgwqe .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#nodnscgwqe .gt_from_md > :first-child {
  margin-top: 0;
}

#nodnscgwqe .gt_from_md > :last-child {
  margin-bottom: 0;
}

#nodnscgwqe .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#nodnscgwqe .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#nodnscgwqe .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#nodnscgwqe .gt_row_group_first td {
  border-top-width: 2px;
}

#nodnscgwqe .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#nodnscgwqe .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#nodnscgwqe .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#nodnscgwqe .gt_last_summary_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nodnscgwqe .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#nodnscgwqe .gt_first_grand_summary_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#nodnscgwqe .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#nodnscgwqe .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nodnscgwqe .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nodnscgwqe .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 1px;
  padding-right: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#nodnscgwqe .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nodnscgwqe .gt_sourcenote {
  font-size: 90%;
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#nodnscgwqe .gt_left {
  text-align: left;
}

#nodnscgwqe .gt_center {
  text-align: center;
}

#nodnscgwqe .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#nodnscgwqe .gt_font_normal {
  font-weight: normal;
}

#nodnscgwqe .gt_font_bold {
  font-weight: bold;
}

#nodnscgwqe .gt_font_italic {
  font-style: italic;
}

#nodnscgwqe .gt_super {
  font-size: 65%;
}

#nodnscgwqe .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#nodnscgwqe .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#nodnscgwqe .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#nodnscgwqe .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#nodnscgwqe .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1"><strong>Variables</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="2" colspan="1"><strong>N</strong></th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2">
        <span class="gt_column_spanner"><strong>Heart Disease</strong></span>
      </th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="2" colspan="1"><strong>p-value</strong><sup class="gt_footnote_marks">2</sup></th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>No heart attack</strong>, N = 390<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Has Heart attack</strong>, N = 356<sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Age of the patient</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Mean (SD)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">50.17 (9.31)</td>
<td class="gt_row gt_center">55.85 (8.82)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Median (IQR)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">51.00 (43.00, 56.00)</td>
<td class="gt_row gt_center">57.00 (50.00, 62.00)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Range</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">28.00, 76.00</td>
<td class="gt_row gt_center">31.00, 77.00</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Sex of the patient</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Female</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">142 (36.4%)</td>
<td class="gt_row gt_center">40 (11.2%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Male</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">248 (63.6%)</td>
<td class="gt_row gt_center">316 (88.8%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Chest pain type</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">typical angina</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">26 (6.67%)</td>
<td class="gt_row gt_center">15 (4.21%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">atypical angina</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">145 (37.2%)</td>
<td class="gt_row gt_center">21 (5.90%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">non-anginal</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">123 (31.5%)</td>
<td class="gt_row gt_center">46 (12.9%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">asymptomatic</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">96 (24.6%)</td>
<td class="gt_row gt_center">274 (77.0%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Resting blood pressure (in mm Hg)</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Mean (SD)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">130.16 (16.14)</td>
<td class="gt_row gt_center">136.15 (17.96)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Median (IQR)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">130.00 (120.00, 140.00)</td>
<td class="gt_row gt_center">136.00 (123.75, 145.00)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Range</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">94.00, 190.00</td>
<td class="gt_row gt_center">92.00, 200.00</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Cholestoral in mg/dl</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center" style="font-weight: bold;">0.005</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Mean (SD)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">238.77 (55.39)</td>
<td class="gt_row gt_center">251.06 (62.46)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Median (IQR)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">231.50 (203.00, 269.00)</td>
<td class="gt_row gt_center">246.00 (212.00, 283.25)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Range</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">85.00, 564.00</td>
<td class="gt_row gt_center">100.00, 603.00</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Fasting blood sugar</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">&lt;= 120mg/dl</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">347 (89.0%)</td>
<td class="gt_row gt_center">274 (77.0%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">&gt;120mg/dl</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">43 (11.0%)</td>
<td class="gt_row gt_center">82 (23.0%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Resting electrocardiographic results</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">normal</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">257 (65.9%)</td>
<td class="gt_row gt_center">188 (52.8%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">having ST_T 
 abnormality</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">52 (13.3%)</td>
<td class="gt_row gt_center">73 (20.5%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">showing probable or 
 definate left
 ventricular hypertrophy</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">81 (20.8%)</td>
<td class="gt_row gt_center">95 (26.7%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Maximum heart rate achieved</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Mean (SD)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">149.06 (23.11)</td>
<td class="gt_row gt_center">130.55 (22.30)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Median (IQR)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">150.50 (135.00, 167.00)</td>
<td class="gt_row gt_center">130.00 (115.00, 147.00)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Range</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">69.00, 202.00</td>
<td class="gt_row gt_center">71.00, 195.00</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Exercise induced angina</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">No</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">340 (87.2%)</td>
<td class="gt_row gt_center">119 (33.4%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Yes</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">50 (12.8%)</td>
<td class="gt_row gt_center">237 (66.6%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">ST depression</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Mean (SD)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.39 (0.68)</td>
<td class="gt_row gt_center">1.46 (1.15)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Median (IQR)</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0.00 (0.00, 0.60)</td>
<td class="gt_row gt_center">1.50 (0.50, 2.00)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Range</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">-0.10, 4.20</td>
<td class="gt_row gt_center">0.00, 6.20</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Slope of peak exercise</td>
<td class="gt_row gt_center">746</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">upsloping</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">304 (77.9%)</td>
<td class="gt_row gt_center">45 (12.6%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">flat</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">75 (19.2%)</td>
<td class="gt_row gt_center">279 (78.4%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">downsloping</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">11 (2.82%)</td>
<td class="gt_row gt_center">32 (8.99%)</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Missing</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center">0</td>
<td class="gt_row gt_center"></td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="5"><sup class="gt_footnote_marks">1</sup> Mean (SD); Median (IQR); Range; Frequency (%)</td>
    </tr>
    <tr>
      <td class="gt_footnote" colspan="5"><sup class="gt_footnote_marks">2</sup> Two Sample t-test; Pearson's Chi-squared test</td>
    </tr>
  </tfoot>
</table>
</div>
</div>
<div id="visualization-1" class="section level3" number="3.2.2">
<h3 number="3.2.2"><span class="header-section-number">3.2.2</span> Visualization</h3>
<pre class="r"><code>p12 &lt;- ggplot(heart_disease_final, aes(x=output))+
  geom_bar(aes(fill = sex), show.legend = TRUE, position=&quot;dodge&quot;)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Sex of the patient&quot;, fill=&quot;&quot;)+
  scale_y_continuous(breaks = seq(0, 350, by = 50), limits = c(0, 350))+
  theme_pubclean()+
  geom_text(aes(fill=sex, label = ..count..), stat = &quot;count&quot;, vjust = 1.2, colour = &quot;black&quot;,
            position = position_dodge(.9))+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        legend.position = &quot;top&quot;,
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())

p13 &lt;- ggplot(heart_disease_final, aes(x=output))+
  geom_bar(aes(fill = cp), show.legend = TRUE, position=&quot;dodge&quot;)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Chest pain Type&quot;, fill=&quot;&quot;)+
  scale_y_continuous(breaks = seq(0, 300, by = 50), limits = c(0, 300))+
  theme_pubclean()+
  geom_text(aes(fill=cp, label = ..count..), stat = &quot;count&quot;, vjust = 0.5, colour = &quot;black&quot;,
            position = position_dodge(.9))+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        legend.position = &quot;top&quot;,
        axis.text.y = element_text(color=&quot;black&quot;,size=12),
        axis.text.x = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())+
  guides(fill = guide_legend(nrow = 2))


p14 &lt;- ggplot(heart_disease_final, aes(x=output))+
  geom_bar(aes(fill = fbs), show.legend = TRUE, position=&quot;dodge&quot;)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Fasting blood sugar&quot;, fill=&quot;&quot;)+
  scale_y_continuous(breaks = seq(0, 350, by = 50), limits = c(0, 350))+
 theme_pubclean()+
  geom_text(aes(fill=fbs, label = ..count..), stat = &quot;count&quot;, vjust = 1.2, colour = &quot;black&quot;,
            position = position_dodge(.9))+
  theme(axis.title= element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        legend.position = &quot;top&quot;,
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())

p15 &lt;- ggplot(heart_disease_final, aes(x=output))+
  geom_bar(aes(fill = restecg), show.legend = TRUE, position=&quot;dodge&quot;)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Resting electrocardiographic results&quot;, fill=&quot;&quot;)+
  scale_y_continuous(breaks = seq(0, 300, by = 50), limits = c(0, 300))+
  theme_pubclean()+
  geom_text(aes(fill=restecg, label = ..count..), stat = &quot;count&quot;, vjust = 1.2, colour = &quot;black&quot;,
            position = position_dodge(.9))+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        legend.position = &quot;top&quot;,
        axis.text.y = element_text(color=&quot;black&quot;,size=12),
        axis.text.x = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())

p16 &lt;- ggplot(heart_disease_final, aes(x=output))+
  geom_bar(aes(fill = exng), show.legend = TRUE, position=&quot;dodge&quot;)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Exercise induced angina&quot;, fill=&quot;&quot;)+
  scale_y_continuous(breaks = seq(0, 350, by = 50), limits = c(0, 350))+
  theme_pubclean()+
  geom_text(aes(fill=exng, label = ..count..), stat = &quot;count&quot;, vjust = 1.2, colour = &quot;black&quot;,
            position = position_dodge(.9))+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        legend.position = &quot;top&quot;,
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())


p17 &lt;- ggplot(heart_disease_final, aes(x=output))+
  geom_bar(aes(fill = slp), show.legend = TRUE, position=&quot;dodge&quot;)+
  labs(x=&quot;&quot;,y=&quot;&quot;, title = &quot;Slope of peak exercise&quot;, fill=&quot;&quot;)+
  scale_y_continuous(breaks = seq(0, 350, by = 50), limits = c(0, 350))+
  theme_pubclean()+
  geom_text(aes(fill=slp, label = ..count..), stat = &quot;count&quot;, vjust = 0.5, colour = &quot;black&quot;,
            position = position_dodge(.9))+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        legend.position = &quot;top&quot;,
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank())

figure3 &lt;- ggarrange( p12, p13, p14, p15, p16, p17, 
          ncol = 3, nrow = 2)

annotate_figure(figure3,
                top = text_grob(&quot;Distribution by Heart disease of various categorical features&quot;,
                                color = &quot;red&quot;, face = &quot;bold&quot;, size = 15),
                bottom = text_grob(&quot;Data source: \n heart disease data set&quot;, color = &quot;blue&quot;,
                                   hjust = 1, x = 0.98, face = &quot;italic&quot;, size = 10),
                #left = text_grob(&quot;Figure arranged using ggpubr&quot;, color = &quot;green&quot;, rot = 90),
                #right = &quot;&quot;,
                fig.lab = &quot;Figure 3&quot;, fig.lab.face = &quot;bold&quot;
                )</code></pre>
<p><img src="Predicting-heart-disease_files/figure-html/grouped%20bar%20graph-1.png" width="1344" /></p>
<pre class="r"><code>p18 &lt;- ggplot(heart_disease_final, aes(x=age, fill=output)) + 
  geom_density(alpha=0.4)+
  scale_y_continuous(n.breaks = 10)+
  scale_x_continuous(breaks = seq(25, 80, by = 5), limits = c(25, 80))+
  labs(x=&quot;age&quot;,y=&quot;density&quot;, title = &quot;Age of the patient&quot;)+
  theme(axis.title = element_text(color=&quot;black&quot;,size=12),
        legend.position = &quot;top&quot;,
        axis.text = element_text(color=&quot;black&quot;,size=11),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())+
  guides(fill = guide_legend(title = &quot;&quot;))


p19 &lt;-ggplot(heart_disease_final, aes(x=trtbps, fill=output)) + 
  geom_density(alpha=0.4)+
  scale_y_continuous(n.breaks = 10)+
  scale_x_continuous(breaks = seq(90, 200, by = 10), limits = c(90, 200))+
  labs(x=&quot;Resting blood pressure (in mm Hg)&quot;,y=&quot;density&quot;, title = &quot;Resting blood pressure&quot;)+
  theme(axis.title = element_text(color=&quot;black&quot;,size=12),
        legend.position = &quot;top&quot;,
        axis.text.y = element_text(color=&quot;black&quot;,size=11),
        axis.text.x = element_text(color=&quot;black&quot;,size=9, angle = 90),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())+
  guides(fill = guide_legend(title = &quot;&quot;))


p20 &lt;-ggplot(heart_disease_final, aes(x=chol, fill=output)) + 
  geom_density(alpha=0.4)+
  scale_y_continuous(n.breaks = 10)+
  scale_x_continuous(breaks = seq(50, 650, by = 50), limits = c(50, 650))+
  labs(x=&quot;cholestoral in mg/dl&quot;,y=&quot;density&quot;, title = &quot;cholestoral&quot;)+
  theme(axis.title = element_text(color=&quot;black&quot;,size=12),
        legend.position = &quot;top&quot;,
        axis.text.y = element_text(color=&quot;black&quot;,size=11),
        axis.text.x = element_text(color=&quot;black&quot;,size=9, angle = 90),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())+
  guides(fill = guide_legend(title = &quot;&quot;))


p21 &lt;-ggplot(heart_disease_final, aes(x=thalach, fill=output)) + 
  geom_density(alpha=0.4)+
  scale_y_continuous(n.breaks = 10)+
  scale_x_continuous(breaks = seq(60, 210, by = 10), limits = c(60, 210))+
  labs(x=&quot;Maximum heart rate achieved&quot;,y=&quot;density&quot;, title = &quot;Maximum heart rate&quot;)+
  theme(axis.title = element_text(color=&quot;black&quot;,size=12),
        legend.position = &quot;top&quot;,
        axis.text.y = element_text(color=&quot;black&quot;,size=11),
        axis.text.x = element_text(color=&quot;black&quot;,size=9, angle=90),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank())+
  guides(fill = guide_legend(title = &quot;&quot;))


p22 &lt;- ggplot(heart_disease_final, aes(output, age))+
  geom_boxplot(aes(colour = output), outlier.colour = &quot;black&quot;, 
               outlier.shape = 8, show.legend = FALSE)+
  labs(x=&quot;&quot;,y=&quot;age&quot;, title = &quot;Age of the patient&quot;)+
  scale_y_continuous(breaks = seq(25, 80, by = 5), limits = c(25, 80))+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank())


p23 &lt;- ggplot(heart_disease_final, aes(output, trtbps))+
  geom_boxplot(aes(colour = output), outlier.colour = &quot;black&quot;, 
               outlier.shape = 1, show.legend = FALSE)+
  labs(x=&quot;&quot;,y=&quot;Resting blood pressure (mm Hg)&quot;, title = &quot;Resting blood pressure&quot;)+
  scale_y_continuous(breaks = seq(90, 200, by = 10), limits = c(90, 200))+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank())


p24 &lt;-ggplot(heart_disease_final, aes(output, chol))+
  geom_boxplot(aes(colour = output), outlier.colour = &quot;black&quot;, 
               outlier.shape = 1, show.legend = FALSE)+
  labs(x=&quot;&quot;,y=&quot;cholestoral in mg/dl&quot;, title = &quot;cholestoral&quot;)+
  scale_y_continuous(breaks = seq(50, 650, by = 50), limits = c(50, 650))+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank())


p25 &lt;-ggplot(heart_disease_final, aes(output, thalach))+
  geom_boxplot(aes(colour = output), outlier.colour = &quot;black&quot;, 
               outlier.shape = 1, show.legend = FALSE)+
  labs(x=&quot;&quot;,y=&quot;Maximum heart rate achieved&quot;, title = &quot;Maximum heart rate&quot;)+
  scale_y_continuous(breaks = seq(60, 200, by = 10), limits = c(60, 200))+
  theme(axis.title = element_text(face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        axis.text = element_text(color=&quot;black&quot;,size=12),
        plot.title = element_text(hjust = 0.5, face=&quot;bold&quot;,color=&quot;black&quot;,size=13),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank())

figure4 &lt;- ggarrange( p18, p19, p20, p21, p22, p23, p24, p25, 
          ncol = 4, nrow = 2)

annotate_figure(figure4,
                top = text_grob(&quot;Distribution by Heart disease of various continous features&quot;,
                                color = &quot;red&quot;, face = &quot;bold&quot;, size = 15),
                bottom = text_grob(&quot;Data source: \n heart disease data set&quot;, color = &quot;blue&quot;,
                                   hjust = 1, x = 0.98, face = &quot;italic&quot;, size = 10),
                #left = text_grob(&quot;Figure arranged using ggpubr&quot;, color = &quot;green&quot;, rot = 90),
                #right = &quot;&quot;,
                fig.lab = &quot;Figure 4&quot;, fig.lab.face = &quot;bold&quot;
                )</code></pre>
<p><img src="Predicting-heart-disease_files/figure-html/density%20and%20box%20plots-1.png" width="1344" /></p>
</div>
<div id="correlation" class="section level3" number="3.2.3">
<h3 number="3.2.3"><span class="header-section-number">3.2.3</span> Correlation</h3>
<p>A negative correlation implies that the two variables under consideration vary in opposite directions, that is, if a variable increases the other decreases and vice versa. On the other hand, a positive correlation implies that the two variables under consideration vary in the same direction, i.e., if a variable increases the other one increases and if one decreases the other one decreases as well</p>
<pre class="r"><code># improved correlation matrix
library(corrplot)

corrplot(cor(heart_disease_final%&gt;%mutate(across(c(2,3,6, 7, 9, 11, 12), as.numeric)),
             method=&#39;spearman&#39;),
  method = &quot;color&quot;, #number
  addCoef.col = &quot;black&quot;,
  number.cex = 0.95,
  type = &quot;upper&quot; # show only upper side #full
)</code></pre>
<p><img src="Predicting-heart-disease_files/figure-html/improved%20correlation-1.png" width="1344" /></p>
<p>Only correlations with p-values smaller than the significance level (p&lt;0.05)should be interpreted.</p>
<pre class="r"><code># correlation tests for whole dataset
library(Hmisc)
res &lt;- rcorr(as.matrix(heart_disease_final%&gt;%mutate(across(c(2,3,6, 7, 9, 11, 12), as.numeric)))) # rcorr() accepts matrices only

# display p-values (rounded to 3 decimals)
kable(
  round(res$P, 3)
)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">age</th>
<th align="right">sex</th>
<th align="right">cp</th>
<th align="right">trtbps</th>
<th align="right">chol</th>
<th align="right">fbs</th>
<th align="right">restecg</th>
<th align="right">thalach</th>
<th align="right">exng</th>
<th align="right">oldpeak</th>
<th align="right">slp</th>
<th align="right">output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">NA</td>
<td align="right">0.264</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.109</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">sex</td>
<td align="right">0.264</td>
<td align="right">NA</td>
<td align="right">0.000</td>
<td align="right">0.349</td>
<td align="right">0.003</td>
<td align="right">0.009</td>
<td align="right">0.713</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.001</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">cp</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">NA</td>
<td align="right">0.235</td>
<td align="right">0.029</td>
<td align="right">0.236</td>
<td align="right">0.032</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">trtbps</td>
<td align="right">0.000</td>
<td align="right">0.349</td>
<td align="right">0.235</td>
<td align="right">NA</td>
<td align="right">0.009</td>
<td align="right">0.000</td>
<td align="right">0.090</td>
<td align="right">0.001</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">chol</td>
<td align="right">0.109</td>
<td align="right">0.003</td>
<td align="right">0.029</td>
<td align="right">0.009</td>
<td align="right">NA</td>
<td align="right">0.141</td>
<td align="right">0.064</td>
<td align="right">0.588</td>
<td align="right">0.018</td>
<td align="right">0.110</td>
<td align="right">0.032</td>
<td align="right">0.005</td>
</tr>
<tr class="even">
<td align="left">fbs</td>
<td align="right">0.000</td>
<td align="right">0.009</td>
<td align="right">0.236</td>
<td align="right">0.000</td>
<td align="right">0.141</td>
<td align="right">NA</td>
<td align="right">0.000</td>
<td align="right">0.005</td>
<td align="right">0.003</td>
<td align="right">0.129</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">restecg</td>
<td align="right">0.000</td>
<td align="right">0.713</td>
<td align="right">0.032</td>
<td align="right">0.090</td>
<td align="right">0.064</td>
<td align="right">0.000</td>
<td align="right">NA</td>
<td align="right">0.488</td>
<td align="right">0.194</td>
<td align="right">0.001</td>
<td align="right">0.003</td>
<td align="right">0.002</td>
</tr>
<tr class="even">
<td align="left">thalach</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.001</td>
<td align="right">0.588</td>
<td align="right">0.005</td>
<td align="right">0.488</td>
<td align="right">NA</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">exng</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.018</td>
<td align="right">0.003</td>
<td align="right">0.194</td>
<td align="right">0.000</td>
<td align="right">NA</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">oldpeak</td>
<td align="right">0.000</td>
<td align="right">0.001</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.110</td>
<td align="right">0.129</td>
<td align="right">0.001</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">NA</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">slp</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.032</td>
<td align="right">0.000</td>
<td align="right">0.003</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">NA</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">output</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.005</td>
<td align="right">0.000</td>
<td align="right">0.002</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<p>After exploring the data, a statistical model will be used to give the final conclusion of the relationship. The dependent variable, “output” is categorical with two variables while the independent variables are more than one and are a mixture of categorical and continuous data and hence a binary logistic model will be applied. This model will be trained and tested and used to make some predictions.</p>
</div>
</div>
</div>
<div id="logistic-regression" class="section level1" number="4">
<h1 number="4"><span class="header-section-number">4</span> Logistic Regression</h1>
<div id="splitting-the-data-for-training-and-testing" class="section level2" number="4.1">
<h2 number="4.1"><span class="header-section-number">4.1</span> Splitting the data for training and testing</h2>
<p>spliting the data in a 80:20 ratio (training:testing). We use set.seed() to make sure that the results are repeatable. We also use the outcome variable, output to stratify. This is to ensure that the distribution of the outcome is comparable in both data sets.</p>
<pre class="r"><code>library(rsample)

set.seed(123)
split &lt;- initial_split(heart_disease_final, prop = 0.8, strata = output)


train &lt;- training(split) 
test &lt;- testing(split)

#initial_time_split() takes the 1st prop samples for training,instead of random selection.

#sample=sample.split(mydata, SplitRatio = 0.80)
#train&lt;-subset(mydata, sample==TRUE)
#test&lt;-subset(mydata, sample==FALSE)</code></pre>
</div>
<div id="model" class="section level2" number="4.2">
<h2 number="4.2"><span class="header-section-number">4.2</span> model</h2>
<pre class="r"><code>glm_logistic_reg &lt;-glm(formula=output~.,data=train, family=&quot;binomial&quot;)


#summary(glm_logistic_reg)</code></pre>
</div>
<div id="model-statistics" class="section level2" number="4.3">
<h2 number="4.3"><span class="header-section-number">4.3</span> model statistics</h2>
<pre class="r"><code>broom::glance(glm_logistic_reg)</code></pre>
<pre><code>## # A tibble: 1 x 8
##   null.deviance df.null logLik   AIC   BIC deviance df.residual  nobs
##           &lt;dbl&gt;   &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;       &lt;int&gt; &lt;int&gt;
## 1          828.     597  -198.  429.  499.     397.         582   598</code></pre>
<pre class="r"><code>#performance::check_collinearity(glm_logistic_reg)

performance::check_model(glm_logistic_reg)</code></pre>
<p><img src="Predicting-heart-disease_files/figure-html/model%20statistics-1.png" width="1344" /></p>
<pre class="r"><code>#performance::performance_accuracy(glm_logistic_reg)

#plot(performance::performance_roc(glm_logistic_reg))</code></pre>
</div>
<div id="model-results" class="section level2" number="4.4">
<h2 number="4.4"><span class="header-section-number">4.4</span> model results</h2>
<pre class="r"><code>tbl_regression(glm_logistic_reg, exponentiate = TRUE, 
    pvalue_fun = ~style_pvalue(.x, digits = 3),
  )%&gt;%
  #add_global_p()%&gt;% # add global p-value for categorical variables
  bold_p(t= 0.05) %&gt;% # bold p-values under a given threshold (default 0.05)
  bold_labels() %&gt;%
  italicize_levels()%&gt;% 
  modify_header(label = &quot;**Logistic regression**&quot;)%&gt;% # update the column header
  add_significance_stars(
    pattern = &quot;{estimate} ({conf.low}-{conf.high}){stars}&quot;,
    hide_ci = TRUE, hide_se = TRUE , hide_p = FALSE) %&gt;%
  modify_header(estimate ~ &quot;**AOR (95% CI)**&quot;) %&gt;%
  modify_footnote(estimate ~ &quot;AOR = Adjusted Odds Ratio, CI = Confidence Interval&quot;, abbreviation = TRUE)</code></pre>
<div id="holxwysgkz" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#holxwysgkz .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 13px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#holxwysgkz .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#holxwysgkz .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#holxwysgkz .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#holxwysgkz .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#holxwysgkz .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#holxwysgkz .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#holxwysgkz .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#holxwysgkz .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#holxwysgkz .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#holxwysgkz .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#holxwysgkz .gt_group_heading {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#holxwysgkz .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#holxwysgkz .gt_from_md > :first-child {
  margin-top: 0;
}

#holxwysgkz .gt_from_md > :last-child {
  margin-bottom: 0;
}

#holxwysgkz .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#holxwysgkz .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#holxwysgkz .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#holxwysgkz .gt_row_group_first td {
  border-top-width: 2px;
}

#holxwysgkz .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#holxwysgkz .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#holxwysgkz .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#holxwysgkz .gt_last_summary_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#holxwysgkz .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#holxwysgkz .gt_first_grand_summary_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#holxwysgkz .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#holxwysgkz .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#holxwysgkz .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#holxwysgkz .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 1px;
  padding-right: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#holxwysgkz .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#holxwysgkz .gt_sourcenote {
  font-size: 90%;
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
}

#holxwysgkz .gt_left {
  text-align: left;
}

#holxwysgkz .gt_center {
  text-align: center;
}

#holxwysgkz .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#holxwysgkz .gt_font_normal {
  font-weight: normal;
}

#holxwysgkz .gt_font_bold {
  font-weight: bold;
}

#holxwysgkz .gt_font_italic {
  font-style: italic;
}

#holxwysgkz .gt_super {
  font-size: 65%;
}

#holxwysgkz .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#holxwysgkz .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#holxwysgkz .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#holxwysgkz .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#holxwysgkz .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Logistic regression</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>AOR (95% CI)</strong><sup class="gt_footnote_marks">1,2</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Age of the patient</td>
<td class="gt_row gt_center">1.03 (1.00-1.06)</td>
<td class="gt_row gt_center">0.069</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Sex of the patient</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Female</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Male</td>
<td class="gt_row gt_center">5.08 (2.62-10.2)***</td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Chest pain type</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">typical angina</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">atypical angina</td>
<td class="gt_row gt_center">0.76 (0.23-2.48)</td>
<td class="gt_row gt_center">0.641</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">non-anginal</td>
<td class="gt_row gt_center">0.87 (0.30-2.56)</td>
<td class="gt_row gt_center">0.801</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">asymptomatic</td>
<td class="gt_row gt_center">3.88 (1.40-11.3)*</td>
<td class="gt_row gt_center" style="font-weight: bold;">0.010</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Resting blood pressure (in mm Hg)</td>
<td class="gt_row gt_center">1.01 (0.99-1.03)</td>
<td class="gt_row gt_center">0.266</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Cholestoral in mg/dl</td>
<td class="gt_row gt_center">1.00 (1.00-1.01)</td>
<td class="gt_row gt_center">0.098</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Fasting blood sugar</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">&lt;= 120mg/dl</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">&gt;120mg/dl</td>
<td class="gt_row gt_center">1.52 (0.75-3.12)</td>
<td class="gt_row gt_center">0.251</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Resting electrocardiographic results</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">normal</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">having ST_T 
 abnormality</td>
<td class="gt_row gt_center">0.95 (0.45-2.02)</td>
<td class="gt_row gt_center">0.885</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">showing probable or 
 definate left
 ventricular hypertrophy</td>
<td class="gt_row gt_center">1.24 (0.65-2.36)</td>
<td class="gt_row gt_center">0.510</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Maximum heart rate achieved</td>
<td class="gt_row gt_center">1.00 (0.99-1.01)</td>
<td class="gt_row gt_center">0.936</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Exercise induced angina</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">No</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">Yes</td>
<td class="gt_row gt_center">2.43 (1.33-4.42)**</td>
<td class="gt_row gt_center" style="font-weight: bold;">0.004</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">ST depression</td>
<td class="gt_row gt_center">1.50 (1.11-2.06)**</td>
<td class="gt_row gt_center" style="font-weight: bold;">0.010</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">Slope of peak exercise</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">upsloping</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">flat</td>
<td class="gt_row gt_center">10.9 (6.10-20.2)***</td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px; font-style: italic;">downsloping</td>
<td class="gt_row gt_center">3.76 (1.17-12.4)*</td>
<td class="gt_row gt_center" style="font-weight: bold;">0.027</td></tr>
  </tbody>
  
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="3"><sup class="gt_footnote_marks">1</sup> *p&lt;0.05; **p&lt;0.01; ***p&lt;0.001</td>
    </tr>
    <tr>
      <td class="gt_footnote" colspan="3"><sup class="gt_footnote_marks">2</sup> AOR = Adjusted Odds Ratio, CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>
<p>Statistically significant variables are Male(Sex), Asymptomatic (chest pain type), Yes (Angina), ST depression, flat (slope of peak exercise) and downsloping (slope of peak exercise).</p>
<p>Having Asymptomatic chest pain type, Angina, flat slope of peak exercise, downsloping slope of peak exercise, high ST depression and being Male are significantly associated with higher odds of having a heart attack. e.g People with Angina are 2.43 times more likely to get heart attack than those with no Angina. Males are 5.08 times more likely to get heart attack than females.</p>
<p>atypical angina chest pain type, non-anginal chest pain type, having ST_T abnormality sesting electrocardiographic results are associated with lower odds of heart attack. However they do not have a significant effect on heart attack.</p>
</div>
</div>
<div id="evaluating-our-model" class="section level1" number="5">
<h1 number="5"><span class="header-section-number">5</span> Evaluating our Model</h1>
<div id="fitting-with-testing-data" class="section level2" number="5.1">
<h2 number="5.1"><span class="header-section-number">5.1</span> Fitting with testing data</h2>
<pre class="r"><code>test$prediction &lt;-predict(glm_logistic_reg, test, type= &quot;response&quot;)

##replacing probabilities with dummies 

test$predicted &lt;- as.factor(ifelse(test$prediction&lt;0.5, &quot;No heart attack&quot;, &quot;Has Heart attack&quot;))

test &lt;- test%&gt;%
  mutate(predicted= factor(predicted, levels = c(&quot;No heart attack&quot;, &quot;Has Heart attack&quot;)))

test1 &lt;- test%&gt;%
  mutate(across(c(predicted, output), fct_rev))
  
##creating a confusion matrix

table(Predicted=test1$predicted, Actual=test1$output)</code></pre>
<pre><code>##                   Actual
## Predicted          Has Heart attack No heart attack
##   Has Heart attack               68              14
##   No heart attack                 3              63</code></pre>
<pre class="r"><code>##getting percentage of misclassification

1-sum(diag(table(Predicted=test1$predicted, Actual=test1$output)))/sum(table(Predicted=test1$predicted, Actual=test1$output))</code></pre>
<pre><code>## [1] 0.1148649</code></pre>
<pre class="r"><code>##getting percentage of accuracy
sum(diag(table(Predicted=test1$predicted, Actual=test1$output)))/sum(table(Predicted=test1$predicted, Actual=test1$output))</code></pre>
<pre><code>## [1] 0.8851351</code></pre>
<pre class="r"><code>##Testing for goodness of fit. 

with(glm_logistic_reg, pchisq(null.deviance - deviance, df.null - df.residual, lower.tail = FALSE))</code></pre>
<pre><code>## [1] 2.407305e-82</code></pre>
</div>
<div id="confussion-matrix" class="section level2" number="5.2">
<h2 number="5.2"><span class="header-section-number">5.2</span> Confussion matrix</h2>
<pre class="r"><code>library(caret)
confusionMatrix(test1$predicted, test1$output)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##                   Reference
## Prediction         Has Heart attack No heart attack
##   Has Heart attack               68              14
##   No heart attack                 3              63
##                                           
##                Accuracy : 0.8851          
##                  95% CI : (0.8225, 0.9316)
##     No Information Rate : 0.5203          
##     P-Value [Acc &gt; NIR] : &lt; 2e-16         
##                                           
##                   Kappa : 0.7713          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.01529         
##                                           
##             Sensitivity : 0.9577          
##             Specificity : 0.8182          
##          Pos Pred Value : 0.8293          
##          Neg Pred Value : 0.9545          
##              Prevalence : 0.4797          
##          Detection Rate : 0.4595          
##    Detection Prevalence : 0.5541          
##       Balanced Accuracy : 0.8880          
##                                           
##        &#39;Positive&#39; Class : Has Heart attack
## </code></pre>
<ul>
<li><p>True positives (TP) we have 68 correctly classified instances of heart attack</p></li>
<li><p>True negatives(TN) we have 63 cases classified as not having heart attack</p></li>
<li><p>False negatives (FN) we have 3 cases our model said the patient didn’t have heart attack and they actually did</p></li>
<li><p>False positives (FP) we have 14 cases our model said a patient did have heart attack, but they actually didn’t</p></li>
<li><p><strong>Sensitivity (Recall)</strong> The true positive rate is 0.9577 meaning from all the patients that had heart attack ; how many did we predict correctly - this equation is <strong>Sensitivity =TP / (TP + FN)</strong></p></li>
<li><p><strong>Specificity</strong> The true negative rate is 0.8182 meaning from all the patients that didn’t have heart attack - how many did we predict correctly - this equation is <strong>Specificity =TN / (TN + FP)</strong></p></li>
<li><p><strong>Positive Predictive Value (Precision)</strong> is 0.8293 meaning from all the classes we predicted as positive, how many were actually positive. equation is <strong>Positive Predictive Value=TP/(TP + FP)</strong></p></li>
<li><p><strong>Negative Predictive Value (Precision)</strong> is 0.9545 meaning from all the classes we predicted as negative, how many were actually negative. equation is <strong>Negative Predictive Value=TN/(TN + FN)</strong></p></li>
<li><p>Accuracy of the model is 88.5% with p value of 2.407305e-82 (less than the default level of significance (0.05)).</p></li>
</ul>
</div>
<div id="roc-curve" class="section level2" number="5.3">
<h2 number="5.3"><span class="header-section-number">5.3</span> ROC curve</h2>
<pre class="r"><code>plot(performance::performance_roc(glm_logistic_reg, new_data = test))</code></pre>
<p><img src="Predicting-heart-disease_files/figure-html/unnamed-chunk-3-1.png" width="1344" /></p>
<ul>
<li>Our model did relatively well and can be used in making predictions</li>
</ul>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
